// projects.js — Your portfolio data file.
// Edit this file to add/update projects. The order here matches the card stack order.
// Index 0 = front/center card, index 19 = near card (lower-left).

const PROJECTS = [
  {
    id: 'project-01',
    title: 'Diagnostic Feature Analysis',
    subtitle: 'Exploratory analysis and classification of breast cancer diagnostic data',
    img: 'tile_images/Diagnostic_Feature_Analysis.png',
    w: 3.35, h: 1.76,
    tags: ['Python', 'Pandas / Scikit-learn', 'Matplotlib / Seaborn', 'Machine Learning'],
    year: '2026',
    github: 'https://github.com/HeidiW-PPP/Diagnostic-Feature-Analysis',
    live: '',
    description: 'An end-to-end exploratory data analysis and machine learning project using the Wisconsin Breast Cancer Diagnostic dataset. Cleaned and visualized feature distributions, correlation heatmaps, and class separability. Trained and evaluated multiple classifiers (logistic regression, decision tree, SVM) to predict malignancy from cell nucleus measurements, with a focus on interpretability and clinically meaningful metrics like recall.',
    images: [],
  },
  {
    id: 'project-02',
    title: 'Project 02',
    subtitle: 'Coming soon',
    img: 'tile_images/tile2.jpg',
    w: 3.35, h: 2.15,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-03',
    title: 'Project 03',
    subtitle: 'Coming soon',
    img: 'tile_images/tile3.jpg',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-04',
    title: 'Project 04',
    subtitle: 'Coming soon',
    img: 'tile_images/tile4.jpg',
    w: 3.35, h: 2.15,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-05',
    title: 'Project 05',
    subtitle: 'Coming soon',
    img: 'tile_images/tile5.jpg',
    w: 2.10, h: 2.35,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-06',
    title: 'Project 06',
    subtitle: 'Coming soon',
    img: 'tile_images/tile6.jpg',
    w: 2.30, h: 2.30,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-07',
    title: 'Project 07',
    subtitle: 'Coming soon',
    img: 'tile_images/tile7.png',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-08',
    title: 'Project 08',
    subtitle: 'Coming soon',
    img: 'tile_images/tile8.png',
    w: 2.75, h: 2.15,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-09',
    title: 'Project 09',
    subtitle: 'Coming soon',
    img: 'tile_images/tile9.png',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-10',
    title: 'Project 10',
    subtitle: 'Coming soon',
    img: 'tile_images/tile10.png',
    w: 2.10, h: 2.35,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-11',
    title: 'Project 11',
    subtitle: 'Coming soon',
    img: 'tile_images/tile11.png',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-12',
    title: 'Project 12',
    subtitle: 'Coming soon',
    img: 'tile_images/tile12.png',
    w: 2.30, h: 2.30,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-13',
    title: 'Project 13',
    subtitle: 'Coming soon',
    img: 'tile_images/tile13.png',
    w: 2.75, h: 2.15,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-14',
    title: 'Project 14',
    subtitle: 'Coming soon',
    img: 'tile_images/tile14.png',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-15',
    title: 'Project 15',
    subtitle: 'Coming soon',
    img: 'tile_images/tile15.png',
    w: 2.10, h: 2.35,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-16',
    title: 'Project 16',
    subtitle: 'Coming soon',
    img: 'tile_images/tile16.png',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-17',
    title: 'Project 17',
    subtitle: 'Coming soon',
    img: 'tile_images/tile17.webp',
    w: 2.75, h: 2.15,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-18',
    title: 'Project 18',
    subtitle: 'Coming soon',
    img: 'tile_images/tile18.webp',
    w: 2.30, h: 2.30,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-19',
    title: 'Project 19',
    subtitle: 'Coming soon',
    img: 'tile_images/tile19.jpg',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
  {
    id: 'project-20',
    title: 'Project 20',
    subtitle: 'Coming soon',
    img: 'tile_images/tile20.jpg',
    w: 1.85, h: 2.50,
    tags: [],
    year: '',
    github: '',
    live: '',
    description: '',
    images: [],
  },
];
